server:
  port: 9527

spring:
  application:
    name: commoncloud-zuul-gateway


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka
    instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true

zuul:
  #配置微服务路由映射地址
  routes:
    #微服务名称
    mydept.serviceId: commoncloud-dept
    #微服务映射的url
    mydept.path: /mydept/**
    #配置后可以杜绝zuul使用微服务名访问接口地址
    ignored-services: commoncloud-dept  #可以使用 "*" 来忽略所有的微服务
    #可以配置路径公共前缀来区分
    prefix: /lhtao

info:
  app.name: lht-commoncloud
  company.name: www.lht.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}